"""empty message

Revision ID: f20af7574337
Revises: 261b0e837f74
Create Date: 2025-05-29 17:19:39.083644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f20af7574337'
down_revision = '261b0e837f74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('nombre', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('precio', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('imagen_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ultima_actualizacion', sa.Date(), nullable=True))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('description')
        batch_op.drop_column('id')
        batch_op.drop_column('created_at')
        batch_op.drop_column('price')
        batch_op.drop_column('name')
        batch_op.drop_column('stock')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('ultima_actualizacion')
        batch_op.drop_column('imagen_url')
        batch_op.drop_column('precio')
        batch_op.drop_column('nombre')
        batch_op.drop_column('codigo')

    # ### end Alembic commands ###
