openapi: 3.0.3
info:
  title: API Lista de Precios
  description: API para consultar productos y administrar listas de precios.
  version: 1.0.0

servers:
  - url: http://localhost:8000
    description: Servidor local

paths:
  /productos:
    get:
      summary: Obtener listado de productos
      parameters:
        - in: query
          name: nombre
          schema:
            type: string
          description: Filtro por nombre del producto
      responses:
        '200':
          description: Lista de productos encontrada
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Producto'
        '204':
          description: No se encontraron productos
        '500':
          description: Error interno del servidor

  /productos/{codigo}:
    get:
      summary: Obtener producto por código
      parameters:
        - in: path
          name: codigo
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Producto encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Producto'
        '404':
          description: Producto no encontrado
        '500':
          description: Error interno del servidor

      security:
        - bearerAuth: []
      responses:
        '201':
          description: Lista subida correctamente
        '400':
          description: Archivo inválido
        '401':
          description: No autorizado
        '500':
          description: Error interno

components:
  schemas:
    Producto:
      type: object
      properties:
        codigo:
          type: string
        nombre:
          type: string
        precio:
          type: number
          format: float
        imagen_url:
          type: string
          format: uri
        ultima_actualizacion:
          type: string
          format: date

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
